Website = "https://github.com/Edw590/VISOR---A-Voice-Assistant"

[Details]
  Icon = "logo/logo_adaptive_all_modded.png"
  Name = "V.I.S.O.R."
  ID = "com.edw590.visor_c"
  Version = "0.0.0"
  Build = 4
